#!/bin/bash
set -e

source params.sh

if test -z "$cronline"
then
  echo cronline var is not defined!
  exit 1
fi

if test -z "$global_name"
then
  echo global_name is blank!
  exit 2
fi

echo using global_name=$global_name

cat <<TTT >/etc/cron.d/zapusk_$global_name
# generated by zapusk
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
$cronline
TTT

echo "generated cron file /etc/cron.d/zapusk_$global_name"
